module.exports.CHANNELS = {
    onNewStation: 'on:new:station',
    onLLn: 'on:ll:n',
    datetime: 'datetime:data',
    onlineStatus: 'online:status',
    ll1On: 'll1:On',
    ll1Off: 'll1:Off',
    ll2On: 'll2:On',
    ll2Off: 'll2:Off',
    ll3On: 'll3:On',
    ll3Off: 'll3:Off',
    ll4On: 'll4:On',
    ll4Off: 'll4:Off',
    ll5On: 'll5:On',
    ll5Off: 'll5:Off',
    ll6On: 'll6:On',
    ll6Off: 'll6:Off',
    ll7On: 'll7:On',
    ll7Off: 'll7:Off',
    ll8On: 'll8:On',
    ll8Off: 'll8:Off',
    ll9On: 'll9:On',
    ll9Off: 'll9:Off',
    ll10On: 'll10:On',
    ll10Off: 'll10:Off',
    ll11On: 'll11:On',
    ll11Off: 'll11:Off',
    ll12On: 'll12:On',
    ll12Off: 'll12:Off',
    ll13On: 'll13:On',
    ll13Off: 'll13:Off',
    ll14On: 'll14:On',
    ll14Off: 'll14:Off',
    ll15On: 'll15:On',
    ll15Off: 'll15:Off',
    autoManual: 'auto:manual',
    setAutoManual: 'set:auto:manual',
    removeLl1: 'removeLl1',
    removeLl2: 'removeLl2',
    removeLl3: 'removeLl3',
    removeLl4: 'removeLl4',
    removeLl5: 'removeLl5',
    removeLl6: 'removeLl6',
    removeLl7: 'removeLl7',
    removeLl8: 'removeLl8',
    removeLl9: 'removeLl9',
    removeLl10: 'removeLl10',
    removeLl11: 'removeLl11',
    removeLl12: 'removeLl12',
    removeLl13: 'removeLl13',
    removeLl14: 'removeLl14',
    removeLl15: 'removeLl15'
}

module.exports.PRESSTIME = 2000;
module.exports.SCANTIME = 1000;